services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/Arthurvini17/larazillow
    plan: free
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_DATABASE
        value: larazillow
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        sync: false
    disk:
      name: storage
      mountPath: /var/www/html/storage
      sizeGB: 1
